# DISCORD
DISCORD_ALU_TOKEN = ''
DISCORD_YEN_TOKEN = ''
DISCORD_BOT_INVLINK = ''

# STEAM (AluBot account)
STEAM_ALU_LGN = ''
STEAM_ALU_PSW = ''

# STEAM (YenBot account)
STEAM_YEN_LGN = ''
STEAM_YEN_PSW = ''

# DOTA 2
DOTA_FRIENDID = 1234

# GIT PERSONAL TOKEN
GIT_PERSONAL_TOKEN = ''

# RIOT
RIOT_API_KEY = ''

# TWITCH
TWITCH_CLIENT_ID = ''
TWITCH_CLIENT_SECRET = ''

# DATABASE
SQL_URL = ''

# ORACLE DATABASE
ORACLE_UN = ''
ORACLE_PW = ''
ORACLE_CS = ""
ORACLE_HOST = ''
ORACLE_PORT = 1234
ORACLE_SERVICE_NAME = ''

# WOLFRAM
WOLFRAM_TOKEN = ""

# REDDIT
REDDIT_CLIENT_ID = ''
REDDIT_CLIENT_SECRET = ''
REDDIT_PASSWORD = ''
REDDIT_USER_AGENT = ''
REDDIT_USERNAME = ''

# DETECTLANGUAGE.COM
DETECTLANGUAGE_API_KEY = ''

# TWITTER
TWITTER_BEARER_TOKEN = ''
