name: Bug report
description: Something behaves in a way it probably should not... Or maybe does not work at all.


labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: >
        
        * For quicker feature request you can dm/@ me in discord or use `/feedback` command.

  - type: input
    attributes:
      label: 🔵Summary
      description: A clear, simple and concise description of what your feature request is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🟣Description.
      description: >
        
        * What would you like this feature to do?
        
        * What problem is your feature trying to solve? 
        
        * What becomes easier or possible when this feature is implemented?

      placeholder: What is the feature?
    validations:
      required: true