blank_issues_enabled: false
contact_links:
  - name: Ask a question in my DMs
    about: Ask questions and discuss with other users of the library.
    url: https://discordapp.com/users/312204139751014400
  - name: Discord Server
    about: Use the Discord server to ask for help and questions as well.
    url: https://discord.gg/K8FuDeP