blank_issues_enabled: false
contact_links:
  - name: Ask a question in my DMs
    about: It's my discord direct messages.
    url: https://discordapp.com/users/312204139751014400
  - name: Discord Server
    about: Use the Discord server to ask for help of my beloved community.
    url: https://discord.gg/K8FuDeP